id = "nvim-nightfox"
name = "Nightfox Themes (Neovim)"
version = "0.4.2"
schema_version = 1
authors = ["Christian Angermann"]
description = "A port of the Neovim Nightfox themes"
repository = "https://github.com/cange/nightfox.zed"
