id = "nvim-nightfox"
name = "Nightfox (Neovim) Themes"
version = "0.1.0"
schema_version = 1
authors = ["Christian Angermann <28717+cange@users.noreply.github.com>"]
description = "A port of the Neovim Nightfox themes"
repository = "https://github.com/cange/nightfox.zed"
