---@meta

---@class nightfox_zed.Metadata
---@field id string
---@field name string
---@field authors table
---@field description string
---@field repository string

---@class nightfox_nvim.PaletteMeta
---@field name string
---@field light boolean

---@class nightfox_nvim.Shade
---@field base string
---@field bright string
---@field dim string
---@field light boolean

---@class nightfox_nvim.Palette
---@field meta nightfox_nvim.PaletteMeta
---@field black nightfox_nvim.Shade
---@field red nightfox_nvim.Shade
---@field green nightfox_nvim.Shade
---@field yellow nightfox_nvim.Shade
---@field blue nightfox_nvim.Shade
---@field magenta nightfox_nvim.Shade
---@field cyan nightfox_nvim.Shade
---@field white nightfox_nvim.Shade
---@field orange nightfox_nvim.Shade
---@field pink nightfox_nvim.Shade
---@field comment string
---@field bg0 string Dark bg (status line and float)
---@field bg1 string Default bg
---@field bg2 string Lighter bg (colorcolm folds)
---@field bg3 string Lighter bg (cursor line)
---@field bg4 string Conceal, border fg
---@field fg0 string Lighter fg
---@field fg1 string Default fg
---@field fg2 string Darker fg (status line)
---@field fg3 string Darker fg (line numbers, fold colums)
---@field sel0 string Popup bg, visual selection bg
---@field sel1 string Popup sel bg, search bg

---@class nightfox_nvim.Spec
---@field bg0 string Dark bg (status line and float)
---@field bg1 string Default bg
---@field bg2 string Lighter bg (colorcolm folds)
---@field bg3 string Lighter bg (cursor line)
---@field bg4 string Conceal, border fg
---@field fg0 string Lighter fg
---@field fg1 string Default fg
---@field fg2 string Darker fg (status line)
---@field fg3 string Darker fg (line numbers, fold colums)
---@field sel0 string Popup bg, visual selection bg
---@field sel1 string Popup sel bg, search bg
---@field syntax nightfox_nvim.SpecSyntax
---@field diag nightfox_nvim.SpecDiagnostic
---@field diag_bg nightfox_nvim.SpecDiagnosticBg
---@field diff nightfox_nvim.SpecDiff
---@field git nightfox_nvim.SpecGit

---@class nightfox_nvim.SpecSyntax
---@field bracket string Brackets and Punctuation
---@field builtin0 string Builtin variable
---@field builtin1 string Builtin type
---@field builtin2 string Builtin const
---@field builtin3 string Not used
---@field comment string Comment
---@field conditional string Conditional and loop
---@field const string Constants, imports and booleans
---@field dep string Deprecated
---@field field string Field
---@field func string Functions and Titles
---@field ident string Identifiers
---@field keyword string Keywords
---@field number string Numbers
---@field operator string Operators
---@field preproc string PreProc
---@field regex string Regex
---@field statement string Statements
---@field string string Strings
---@field type string Types
---@field variable string Variables

---@class nightfox_nvim.SpecDiagnostic
---@field error string
---@field warn string
---@field info string
---@field hint string
---@field ok string

---@class nightfox_nvim.SpecDiagnosticBg
---@field error string
---@field warn string
---@field info string
---@field hint string
---@field ok string

---@class nightfox_nvim.SpecDiff
---@field add string
---@field delete string
---@field change string
---@field text string

---@class nightfox_nvim.SpecGit
---@field add string
---@field changed string
---@field conflict string
---@field ignored string
---@field removed string

---@class nightfox_zed.PlayerColor
---@field cursor string
---@field background string
---@field selection string

---@class nightfox_zed.HighlightStyle
---@field color string
---@field font_weight string
---@field font_style string
---@field background_color string
---@field underline string
---@field strikethrough string
---@field fade_out string
