local M = {}
function M.one_theme()
  return {
    name = "One Dark (dev)",
    appearance = "dark",
    style = {
      border = "#464b57ff",
      ["border.variant"] = "#363c46ff",
      ["border.focused"] = "#47679eff",
      ["border.selected"] = "#293b5bff",
      ["border.transparent"] = "#00000000",
      ["border.disabled"] = "#414754ff",
      ["elevated_surface.background"] = "#2f343eff",
      ["surface.background"] = "#2f343eff",
      background = "#ff414dff",
      ["element.background"] = "#2eff3eff",
      ["element.hover"] = "#363cffff",
      ["element.active"] = "#454a56ff",
      ["element.selected"] = "#454a56ff",
      ["element.disabled"] = "#2e343eff",
      ["drop_target.background"] = "#83899480",
      ["ghost_element.background"] = "#00000000",
      ["ghost_element.hover"] = "#363c46ff",
      ["ghost_element.active"] = "#454a56ff",
      ["ghost_element.selected"] = "#454a56ff",
      ["ghost_element.disabled"] = "#2e343eff",
      text = "#dce0e5ff",
      ["text.muted"] = "#a9afbcff",
      ["text.placeholder"] = "#878a98ff",
      ["text.disabled"] = "#878a98ff",
      ["text.accent"] = "#74ade8ff",
      icon = "#dce0e5ff",
      ["icon.muted"] = "#a9afbcff",
      ["icon.disabled"] = "#878a98ff",
      ["icon.placeholder"] = "#a9afbcff",
      ["icon.accent"] = "#74ade8ff",
      ["status_bar.background"] = "#3b414dff",
      ["title_bar.background"] = "#3b414dff",
      ["title_bar.inactive_background"] = "#2e343eff",
      ["toolbar.background"] = "#282c33ff",
      ["tab_bar.background"] = "#2f343eff",
      ["tab.inactive_background"] = "#2f343eff",
      ["tab.active_background"] = "#282c33ff",
      ["search.match_background"] = "#74ade866",
      ["panel.background"] = "#2f343eff",
      ["panel.focused_border"] = nil,
      ["pane.focused_border"] = nil,
      ["scrollbar.thumb.background"] = "#c8ccd44c",
      ["scrollbar.thumb.hover_background"] = "#363c46ff",
      ["scrollbar.thumb.border"] = "#363c46ff",
      ["scrollbar.track.background"] = "#00000000",
      ["scrollbar.track.border"] = "#2e333cff",
      ["editor.foreground"] = "#acb2beff",
      ["editor.background"] = "#282c33ff",
      ["editor.gutter.background"] = "#282c33ff",
      ["editor.subheader.background"] = "#2f343eff",
      ["editor.active_line.background"] = "#2f343ebf",
      ["editor.highlighted_line.background"] = "#2f343eff",
      ["editor.line_number"] = "#4e5a5f",
      ["editor.active_line_number"] = "#d0d4da",
      ["editor.hover_line_number"] = "#acb0b4",
      ["editor.invisible"] = "#878a98ff",
      ["editor.wrap_guide"] = "#c8ccd40d",
      ["editor.active_wrap_guide"] = "#c8ccd41a",
      ["editor.document_highlight.read_background"] = "#74ade81a",
      ["editor.document_highlight.write_background"] = "#555a6366",
      ["terminal.background"] = "#282c33ff",
      ["terminal.foreground"] = "#dce0e5ff",
      ["terminal.bright_foreground"] = "#dce0e5ff",
      ["terminal.dim_foreground"] = "#282c33ff",
      ["terminal.ansi.black"] = "#282c33ff",
      ["terminal.ansi.bright_black"] = "#525561ff",
      ["terminal.ansi.dim_black"] = "#dce0e5ff",
      ["terminal.ansi.red"] = "#d07277ff",
      ["terminal.ansi.bright_red"] = "#673a3cff",
      ["terminal.ansi.dim_red"] = "#eab7b9ff",
      ["terminal.ansi.green"] = "#a1c181ff",
      ["terminal.ansi.bright_green"] = "#4d6140ff",
      ["terminal.ansi.dim_green"] = "#d1e0bfff",
      ["terminal.ansi.yellow"] = "#dec184ff",
      ["terminal.ansi.bright_yellow"] = "#e5c07bff",
      ["terminal.ansi.dim_yellow"] = "#f1dfc1ff",
      ["terminal.ansi.blue"] = "#74ade8ff",
      ["terminal.ansi.bright_blue"] = "#385378ff",
      ["terminal.ansi.dim_blue"] = "#bed5f4ff",
      ["terminal.ansi.magenta"] = "#be5046ff",
      ["terminal.ansi.bright_magenta"] = "#5e2b26ff",
      ["terminal.ansi.dim_magenta"] = "#e6a79eff",
      ["terminal.ansi.cyan"] = "#6eb4bfff",
      ["terminal.ansi.bright_cyan"] = "#3a565bff",
      ["terminal.ansi.dim_cyan"] = "#b9d9dfff",
      ["terminal.ansi.white"] = "#dce0e5ff",
      ["terminal.ansi.bright_white"] = "#dce0e5ff",
      ["terminal.ansi.dim_white"] = "#575d65ff",
      ["link_text.hover"] = "#74ade8ff",
      ["version_control.added"] = "#27a657ff",
      ["version_control.modified"] = "#d3b020ff",
      ["version_control.deleted"] = "#e06c76ff",
      conflict = "#dec184ff",
      ["conflict.background"] = "#dec1841a",
      ["conflict.border"] = "#5d4c2fff",
      created = "#a1c181ff",
      ["created.background"] = "#a1c1811a",
      ["created.border"] = "#38482fff",
      deleted = "#d07277ff",
      ["deleted.background"] = "#d072771a",
      ["deleted.border"] = "#4c2b2cff",
      error = "#d07277ff",
      ["error.background"] = "#d072771a",
      ["error.border"] = "#4c2b2cff",
      hidden = "#878a98ff",
      ["hidden.background"] = "#696b771a",
      ["hidden.border"] = "#414754ff",
      hint = "#788ca6ff",
      ["hint.background"] = "#5a6f891a",
      ["hint.border"] = "#293b5bff",
      ignored = "#878a98ff",
      ["ignored.background"] = "#696b771a",
      ["ignored.border"] = "#464b57ff",
      info = "#74ade8ff",
      ["info.background"] = "#74ade81a",
      ["info.border"] = "#293b5bff",
      modified = "#dec184ff",
      ["modified.background"] = "#dec1841a",
      ["modified.border"] = "#5d4c2fff",
      predictive = "#5a6a87ff",
      ["predictive.background"] = "#5a6a871a",
      ["predictive.border"] = "#38482fff",
      renamed = "#74ade8ff",
      ["renamed.background"] = "#74ade81a",
      ["renamed.border"] = "#293b5bff",
      success = "#a1c181ff",
      ["success.background"] = "#a1c1811a",
      ["success.border"] = "#38482fff",
      unreachable = "#a9afbcff",
      ["unreachable.background"] = "#8389941a",
      ["unreachable.border"] = "#464b57ff",
      warning = "#dec184ff",
      ["warning.background"] = "#dec1841a",
      ["warning.border"] = "#5d4c2fff",
      players = {
        {
          cursor = "#74ade8ff",
          background = "#74ade8ff",
          selection = "#74ade83d",
        },
        {
          cursor = "#be5046ff",
          background = "#be5046ff",
          selection = "#be50463d",
        },
        {
          cursor = "#bf956aff",
          background = "#bf956aff",
          selection = "#bf956a3d",
        },
        {
          cursor = "#b477cfff",
          background = "#b477cfff",
          selection = "#b477cf3d",
        },
        {
          cursor = "#6eb4bfff",
          background = "#6eb4bfff",
          selection = "#6eb4bf3d",
        },
        {
          cursor = "#d07277ff",
          background = "#d07277ff",
          selection = "#d072773d",
        },
        {
          cursor = "#dec184ff",
          background = "#dec184ff",
          selection = "#dec1843d",
        },
        {
          cursor = "#a1c181ff",
          background = "#a1c181ff",
          selection = "#a1c1813d",
        },
      },
      syntax = {
        attribute = {
          color = "#74ade8ff",
          font_style = nil,
          font_weight = nil,
        },
        boolean = {
          color = "#bf956aff",
          font_style = nil,
          font_weight = nil,
        },
        comment = {
          color = "#5d636fff",
          font_style = nil,
          font_weight = nil,
        },
        ["comment.doc"] = {
          color = "#878e98ff",
          font_style = nil,
          font_weight = nil,
        },
        constant = {
          color = "#dfc184ff",
          font_style = nil,
          font_weight = nil,
        },
        constructor = {
          color = "#73ade9ff",
          font_style = nil,
          font_weight = nil,
        },
        embedded = {
          color = "#dce0e5ff",
          font_style = nil,
          font_weight = nil,
        },
        emphasis = {
          color = "#74ade8ff",
          font_style = nil,
          font_weight = nil,
        },
        ["emphasis.strong"] = {
          color = "#bf956aff",
          font_style = nil,
          font_weight = 700,
        },
        enum = {
          color = "#d07277ff",
          font_style = nil,
          font_weight = nil,
        },
        ["function"] = {
          color = "#73ade9ff",
          font_style = nil,
          font_weight = nil,
        },
        hint = {
          color = "#788ca6ff",
          font_style = nil,
          font_weight = 700,
        },
        keyword = {
          color = "#b477cfff",
          font_style = nil,
          font_weight = nil,
        },
        label = {
          color = "#74ade8ff",
          font_style = nil,
          font_weight = nil,
        },
        link_text = {
          color = "#73ade9ff",
          font_style = "normal",
          font_weight = nil,
        },
        link_uri = {
          color = "#6eb4bfff",
          font_style = nil,
          font_weight = nil,
        },
        number = {
          color = "#bf956aff",
          font_style = nil,
          font_weight = nil,
        },
        operator = {
          color = "#6eb4bfff",
          font_style = nil,
          font_weight = nil,
        },
        predictive = {
          color = "#5a6a87ff",
          font_style = "italic",
          font_weight = nil,
        },
        preproc = {
          color = "#dce0e5ff",
          font_style = nil,
          font_weight = nil,
        },
        primary = {
          color = "#acb2beff",
          font_style = nil,
          font_weight = nil,
        },
        property = {
          color = "#d07277ff",
          font_style = nil,
          font_weight = nil,
        },
        punctuation = {
          color = "#acb2beff",
          font_style = nil,
          font_weight = nil,
        },
        ["punctuation.bracket"] = {
          color = "#b2b9c6ff",
          font_style = nil,
          font_weight = nil,
        },
        ["punctuation.delimiter"] = {
          color = "#b2b9c6ff",
          font_style = nil,
          font_weight = nil,
        },
        ["punctuation.list_marker"] = {
          color = "#d07277ff",
          font_style = nil,
          font_weight = nil,
        },
        ["punctuation.special"] = {
          color = "#b1574bff",
          font_style = nil,
          font_weight = nil,
        },
        string = {
          color = "#a1c181ff",
          font_style = nil,
          font_weight = nil,
        },
        ["string.escape"] = {
          color = "#878e98ff",
          font_style = nil,
          font_weight = nil,
        },
        ["string.regex"] = {
          color = "#bf956aff",
          font_style = nil,
          font_weight = nil,
        },
        ["string.special"] = {
          color = "#bf956aff",
          font_style = nil,
          font_weight = nil,
        },
        ["string.special.symbol"] = {
          color = "#bf956aff",
          font_style = nil,
          font_weight = nil,
        },
        tag = {
          color = "#74ade8ff",
          font_style = nil,
          font_weight = nil,
        },
        ["text.literal"] = {
          color = "#a1c181ff",
          font_style = nil,
          font_weight = nil,
        },
        title = {
          color = "#d07277ff",
          font_style = nil,
          font_weight = 400,
        },
        ["type"] = {
          color = "#6eb4bfff",
          font_style = nil,
          font_weight = nil,
        },
        variable = {
          color = "#acb2beff",
          font_style = nil,
          font_weight = nil,
        },
        ["variable.special"] = {
          color = "#bf956aff",
          font_style = nil,
          font_weight = nil,
        },
        variant = {
          color = "#73ade9ff",
          font_style = nil,
          font_weight = nil,
        },
      },
    },
  }
end

return M
