---
name: pr

"on":
  push:
    pull_request:

permissions:
  contents: write

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run linter
        uses: JohnnyMorganz/stylua-action@v5
        with:
          args: --check .
          token: ${{ secrets.GITHUB_TOKEN }}
          version: 2.5.2
