---
name: "Release Zed Extension"

"on":
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: huacnlee/zed-extension-action@v2
        with:
          extension-name: nvim-nightfox
          push-to: cange/extensions
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
